import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Button } from "antd";
import { useActions } from "hooks/useActions";
import { useTypedSelector } from "hooks/useTypeSelector";
import { useFetchAuthMutation } from "services/authService";

const Home: NextPage = () => {
  const { setUserName } = useActions();
  const { name } = useTypedSelector((state) => state.userReducer);
  const [fetchAuth] = useFetchAuthMutation();

  const handleClick = () => {
    setUserName("sdf");
    fetchAuth({ email: "femakeoverweb@gmail.com", password: "root" });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>English exercise</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Button type="primary" onClick={handleClick}>
          Button
        </Button>
        {name}
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
