import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/home.module.css";
import MainLayout from "../components/layouts/MainLayout";
import Header from "../components/for-pages/home/Header";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>English exercise</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <MainLayout>
          <Header />
        </MainLayout>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
